default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  port: 5432

development:
  <<: *default
  database: tech_book_review_development
  username: postgres
  password: <%= ENV["TECH_BOOK_REVIEW_DATABASE_PASSWORD"] %>
  host: localhost
  port: 5432

test:
  <<: *default
  database: tech_book_review_test

production:
  <<: *default
  database: tech_book_review_production
  url: <%= ENV["DATABASE_URL"] %>
