default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  port: 5432

development:
  <<: *default
  database: tech_book_review_development
  username: postgres
  password: <%= ENV["TECH_BOOK_REVIEW_DATABASE_PASSWORD"] %>
  host: localhost
  port: 5432

test:
  <<: *default
  database: tech_book_review_test

#tech_book_review_productionに名前変えたい
production:
  <<: *default
  database: tech_book_review_api
  username: tech_book_review_api_user
  password: <%= ENV['TECH_BOOK_REVIEW_DATABASE_PASSWORD'] %>
  host: dpg-cu0h9v5ds78s73ddvfj0-a.oregon-postgres.render.com
  url: <%= ENV['DATABASE_URL'] %>
  port: 5432

